// This file is generated by tools/generate.js. DO NOT EDIT.
/**
 * Copyright Planet Labs PBC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {MapboxVectorLayer as OLMBVectorLayer} from 'ol-mapbox-style';
import propTypes from 'prop-types';
import {createElement} from 'react';

export default function MapboxVector({children, ...props}) {
  return createElement('layer', {cls: OLMBVectorLayer, ...props}, children);
}

MapboxVector.propTypes = {
  children: propTypes.node,
};
