// This file is generated by tools/generate.js. DO NOT EDIT.
/**
 * Copyright 2023 Planet Labs PBC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import OLVector from 'ol/layer/Vector.js';
import propTypes from 'prop-types';
import {createElement, forwardRef} from 'react';

const Vector = forwardRef(({children, ...props}, ref) => {
  return createElement('layer', {cls: OLVector, ref, ...props}, children);
});

Vector.propTypes = {
  children: propTypes.node,
};

export default Vector;
